# Generated by Django 4.2.5 on 2024-12-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pay_link_pay_session_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='pay',
            name='summ',
            field=models.IntegerField(verbose_name='Сумма'),
        ),
    ]
