# Generated by Django 5.1 on 2024-09-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_subscribe',
            field=models.BooleanField(default=False, verbose_name='подписка'),
        ),
    ]
